/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guis;

/**
 *
 * @author J.Fernando <josefer.hernandez@hotmail.com>
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        this.setTitle("Configuración de Partida");
        this.setResizable(false);//Modifica tamaño ventana
        this.setLocationRelativeTo(null);//Centrar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoLateral = new javax.swing.JPanel();
        btnChico = new javax.swing.JButton();
        btnMediano = new javax.swing.JButton();
        btnGrande = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChico.setText("Chico");
        btnChico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChicoActionPerformed(evt);
            }
        });
        fondoLateral.add(btnChico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        btnMediano.setText("Mediano");
        btnMediano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedianoActionPerformed(evt);
            }
        });
        fondoLateral.add(btnMediano, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        btnGrande.setText("Grande");
        btnGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrandeActionPerformed(evt);
            }
        });
        fondoLateral.add(btnGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        getContentPane().add(fondoLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 480, 390));

        jLabel1.setText("Escoge el tamaño del tablero:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChicoActionPerformed

    private void btnMedianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedianoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedianoActionPerformed

    private void btnGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrandeActionPerformed
        Partida partida = new Partida();
        partida.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGrandeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChico;
    private javax.swing.JButton btnGrande;
    private javax.swing.JButton btnMediano;
    private javax.swing.JPanel fondoLateral;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
