/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guis;

/**
 *
 * @author J.Fernando <josefer.hernandez@hotmail.com>
 */
public class Partida extends javax.swing.JFrame {

    /**
     * Creates new form Partida
     */
    public Partida() {
        initComponents();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero = new javax.swing.JPanel();
        fondoLateral = new javax.swing.JPanel();
        btnLlenar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 77, 27));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablero.setBackground(new java.awt.Color(102, 77, 27));
        tablero.setPreferredSize(new java.awt.Dimension(800, 650));

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        btnLlenar.setText("Llenar");
        btnLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLateralLayout = new javax.swing.GroupLayout(fondoLateral);
        fondoLateral.setLayout(fondoLateralLayout);
        fondoLateralLayout.setHorizontalGroup(
            fondoLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLlenar)
                .addGap(107, 107, 107))
        );
        fondoLateralLayout.setVerticalGroup(
            fondoLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLateralLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnLlenar)
                .addContainerGap(566, Short.MAX_VALUE))
        );

        getContentPane().add(fondoLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 40, 100, 660));

        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarActionPerformed
        Component c = new Casilla();
        Component t = new Tablero((Casilla) c);
        t.dibujar(tablero.getGraphics());
    }//GEN-LAST:event_btnLlenarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLlenar;
    private javax.swing.JPanel fondoLateral;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
